### PR TITLE
Restart recording properly when refreshing.

### LINKED ISSUE #205: Recording crashes on refresh
STR:

1. start recording
2. refresh (cmd + r)

https://www.loom.com/share/f5190ade74b44414a2f72451406f5f0c

Screen Shot 2020-11-16 at 6 38 32 PM

### PR DESCRIPTION
**Pull request by loganfsmyth**
Looks like this is just fixing behavior that was there before so nothing too complicated. In testing, I got an exception from my `getBrowserForPid` function, so I guess there's at least a bit of a race between `remoteTab` being created, and the `RecordingStarted` message from the child process.

Fixes #205

### CODE REVIEW

File: browser/base/content/utilityOverlay.js [hunk 1]
```diff
@@ -640,7 +640,7 @@ function openLinkIn(url, where, params) {
         targetBrowser.currentURI.spec != "about:blank"
       ) {
         w.gBrowser.updateBrowserRemoteness(targetBrowser, {
-          recordExecution: "*",
+          recordExecution: browser.hasAttribute("recordExecution"),
```
Comment (bhackett1024) [inline browser/base/content/utilityOverlay.js]: Should this be getAttribute?

**Review by bhackett1024 — APPROVED** [review]

File: browser/base/content/utilityOverlay.js (hunk 1 above)
Comment (loganfsmyth) [reply browser/base/content/utilityOverlay.js]: Yep! I noticed right after hitting submit but you beat me to it :P
