### PR TITLE
Fix preallocation-related crash.

### LINKED ISSUE #481: Fix crashiness of preallocated recording content processes
Preallocation of recorded browsers is behind a pref because it causes the browser to get crashy.

### PR DESCRIPTION
**Pull request by kannanvijayan**

### CODE REVIEW

File: dom/ipc/ContentParent.cpp [hunk 1]
```diff
@@ -916,10 +916,13 @@ already_AddRefed<ContentParent> ContentParent::GetUsedBrowserProcess(
   // new tabs to not render. There might be a simple fix here but it doesn't
   // seem worth investigating.
   if (aRecordingDispatchAddress.Length() > 0) {
-      return GetUsedBrowserProcessForRecording(
-        aRemoteType, aContentParents, aRecordingDispatchAddress);
+    return GetUsedBrowserProcessForRecording(
+      aRemoteType, aContentParents, aRecordingDispatchAddress);
   }
 
+  return nullptr;
```
Comment (bhackett1024) [inline dom/ipc/ContentParent.cpp:923]: This should have a comment, can you move the one above the if statement here, since it doesn't apply to the if statement anymore?

**Review by bhackett1024 — APPROVED** [review]
