### PR TITLE
Fix connection authentication issue (#598)

### LINKED ISSUE #598: Connection has not been authenticated
The Replay browser can occasionally get into a bad state where you cannot record. Ryan fixed this by clearing his API Key, but Jon also hit the issue and i dont think he has an API Key. I get out of the issue when i see it by quitting and re-opening.

https://ui.honeycomb.io/replay/datasets/backend/result/dLXvB9fen1M

image

### PR DESCRIPTION
**Pull request by hbenl**
[Some context](https://github.com/RecordReplay/gecko-dev/issues/598#issuecomment-994793969)
With this PR, we use `RECORD_REPLAY_API_KEY` only for receiving an API key from the user, and use `RECORD_REPLAY_AUTH` for the internal communication.

### CODE REVIEW

File: toolkit/recordreplay/ProcessRecordReplay.cpp [hunk 1]
```diff
@@ -308,7 +308,7 @@ MOZ_EXPORT void RecordReplayInterface_Initialize(int* aArgc, char*** aArgv) {
   MOZ_RELEASE_ASSERT(dispatchAddress.isSome());
 
   Maybe<std::string> apiKey;
-  const char* val = getenv("RECORD_REPLAY_API_KEY");
+  const char* val = getenv("RECORD_REPLAY_AUTH");
```
Comment (bhackett1024) [inline toolkit/recordreplay/ProcessRecordReplay.cpp:313]: I don't think this is right, this will cause the browser to no longer recognize RECORD_REPLAY_API_KEY.  I think we need to check for both environment variables here.

File: devtools/server/actors/replay/connection.js [hunk 2]
```diff
@@ -221,8 +221,10 @@ gCommandSocket.onStateChange = state => {
   }
 }
 
+setenv("RECORD_REPLAY_AUTH", null);
```
Comment (bhackett1024) [inline devtools/server/actors/replay/connection.js:229]: It would be nice to have a comment about why we clear this on startup.

**Review by bhackett1024 — CHANGES_REQUESTED** [review]

File: toolkit/recordreplay/ProcessRecordReplay.cpp (hunk 1 above)
Comment (hbenl) [reply toolkit/recordreplay/ProcessRecordReplay.cpp:313]: RECORD_REPLAY_API_KEY will also be copied to RECORD_REPLAY_AUTH during initialization, just like the user's token is copied to it if there is no API key. Both happen in the `setAccessToken()` function now.

Comment (bhackett1024) [reply toolkit/recordreplay/ProcessRecordReplay.cpp:313]: Cool, thanks!  It would be nice to have some comments on this logic to explain what's going on (echoing my other comment on the patch).

**Review by bhackett1024 — APPROVED** [review]

File: toolkit/recordreplay/ProcessRecordReplay.cpp [hunk 3]
```diff
@@ -317,9 +319,9 @@ MOZ_EXPORT void RecordReplayInterface_Initialize(int* aArgc, char*** aArgv) {
     // existed and won't capture it in the recording itself, which
     // is ideal for security.
 #ifdef XP_WIN
```
Comment (loganfsmyth) [inline toolkit/recordreplay/ProcessRecordReplay.cpp:321]: It seems like we'd need to duplicate this code rather than changing it, otherwise `RECORD_REPLAY_API_KEY` will still exist in this environment _also_?

Comment (hbenl) [reply toolkit/recordreplay/ProcessRecordReplay.cpp:321]: Good point. Out of curiosity:
- how can these variables be captured in the recording?
- what is this code actually removing? It's not removing the process' environment variables, otherwise we wouldn't have had the authentication issue in the first place. Is it working on a copy of these variables?

Comment (hbenl) [reply toolkit/recordreplay/ProcessRecordReplay.cpp:321]: Fixed in #640
