### PR TITLE
Assert in DecodedSurfaceProvider::Run.

### LINKED ISSUE #773: Assert `this` in DecodeSurfaceProvider::Run
See loom https://www.loom.com/share/4b6ca4a4a46d48ecb964c622d31fcb96

The last common point of execution seems to be within `DecodedSurfaceProvider::Run` method, which calls into `DecodedSurfaceProvider::FinishDecoding`.  Let's replay-assert that we're working with the same underlying object.

Narrows [backend#823](https://github.com/RecordReplay/backend/issues/823)

```
{
  "Timestamp": "2022-03-24T06:28:25.727Z",
  "controlId": "7f8a4204-d2db-4873-9082-fc28613a8d8b",
  "event.date": "Thu, 24 Mar 2022",
  "level": "error",
  "message": "TelemetryEvent",
  "recordingId": "0e77781d-3c84-476a-93d1-59ff694a6784",
  "service_name": "telemetry-server",
  "telemetry.category": "ControllerFinished",
  "telemetry.data.buildId": "windows-gecko-20220322-4afd64f9d1cc-171e5c632610",
  "telemetry.data.buildMetadata.brand": "replay",
  "telemetry.data.buildMetadata.date": "20220322",
  "telemetry.data.buildMetadata.platform": "windows",
  "telemetry.data.buildMetadata.runtime": "gecko",
  "telemetry.data.controlId": "7f8a4204-d2db-4873-9082-fc28613a8d8b",
  "telemetry.data.crashReport.bucket": "issue823",
  "telemetry.data.crashReport.buildId": "windows-gecko-20220322-4afd64f9d1cc-171e5c632610",
  "telemetry.data.crashReport.controlId": "7f8a4204-d2db-4873-9082-fc28613a8d8b",
  "telemetry.data.crashReport.description": "Mismatch OrderedLock ThreadEventQueue",
  "telemetry.data.crashReport.linkerVersion": "linker-windows-8481-171e5c632610",
  "telemetry.data.crashReport.process.backtrace": {
    "frames": [
      "mozilla::image::RawAccessFrameRef::RawAccessFrameRef+62",
      "mozilla::image::imgFrame::RawAccessRef+25",
      "mozilla::image::Decoder::AllocateFrameInternal+814",
      "mozilla::image::Decoder::AllocateFrame+68",
      "mozilla::image::SurfaceSink::Configure+61",
      "mozilla::image::SurfacePipeFactory::MakePipe<mozilla::image::SurfaceConfig>+84",
      "mozilla::image::SurfacePipeFactory::CreateSurfacePipe+4092",
      "mozilla::image::nsJPEGDecoder::ReadJPEGData+3433",
      "mozilla::image::StreamingLexer<mozilla::image::nsJPEGDecoder::State,16>::ContinueUnbufferedRead<`lambda.at.c:/Users/Administrator/recordreplay/gecko-dev/image/decoders/nsJPEGDecoder.cpp:183:21'>+94",
      "mozilla::image::nsJPEGDecoder::DoDecode+1048",
      "mozilla::image::Decoder::Decode+296",
      "mozilla::image::DecodedSurfaceProvider::Run+87",
      "mozilla::image::DecodePool::SyncRunIfPossible+247",
      "mozilla::image::LaunchDecodingTask+129",
      "mozilla::image::RasterImage::Decode+736",
      "mozilla::image::RasterImage::LookupFrame+454",
      "mozilla::image::RasterImage::GetFrameInternal+160",
      "mozilla::image::RasterImage::GetFrameAtSize+238",
      "nsLayoutUtils::SurfaceFromElement+804",
      "nsLayoutUtils::SurfaceFromElement+166",
      ... REST OF FRAMES REMOVED ...
    ],
    "threadId": 1
  },
  "telemetry.data.crashReport.process.recorded": "OrderedLock ThreadEventQueue 17",
  "telemetry.data.crashReport.process.recordedStack": [
    "mozilla::ThreadEventQueue::PutEventInternal+224",
    "mozilla::ThreadEventTarget::Dispatch+141",
    "nsThread::Dispatch+91",
    "NS_DispatchToCurrentThread+76",
    "mozilla::SchedulerGroup::InternalUnlabeledDispatch+61",
    "mozilla::SchedulerGroup::LabeledDispatch+131",
    "mozilla::image::IDecodingTask::NotifyDecodeComplete+1535",
    "mozilla::image::DecodedSurfaceProvider::FinishDecoding+93"
  ],
  "telemetry.data.crashReport.process.replayed": "OrderedLock imgFrame 2789",
  "telemetry.data.crashReport.process.threadId": 1,
  "telemetry.data.crashReport.process.why": "Mismatch",
  "telemetry.data.crashReport.recordingId": "0e77781d-3c84-476a-93d1-59ff694a6784",
  "telemetry.data.crashReport.why": "NoProgress",
  "telemetry.data.fatalError": true,
  "telemetry.data.recording.userEmail": "yangwenguan@gmail.com",
  "telemetry.data.recording.userId": "d0180c2d-222d-4d89-9613-4d6646a79158",
  "telemetry.data.recording.userPriority": 5,
  "telemetry.data.recordingId": "0e77781d-3c84-476a-93d1-59ff694a6784",
  "telemetry.data.sessionErrorCode": 5,
  "telemetry.data.sessionErrorMessage": "Session died due to an unknown error while replaying",
  "telemetry.data.success": "n/a",
  "telemetry.data.timestamp": 1648103305727,
  "telemetry.userIpAddr": "172.16.69.15",
  "triage.failureRate": 100,
  "userEmail": "yangwenguan@gmail.com"
}
```

### PR DESCRIPTION
**Pull request by kannanvijayan**
For issue #773

### CODE REVIEW

File: image/DecodedSurfaceProvider.cpp [hunk 1]
```diff
@@ -113,6 +118,8 @@ size_t DecodedSurfaceProvider::LogicalSizeInBytes() const {
 
 void DecodedSurfaceProvider::Run() {
   MutexAutoLock lock(mMutex);
+  recordreplay::RecordReplayAssert("DecodedSurfaceProvider::Run %u",
+    (unsigned) recordreplay::ThingIndex(this));
```
Comment (bhackett1024) [inline image/DecodedSurfaceProvider.cpp:124]: These assertions should have a comment referencing the issue.

**Review by bhackett1024 — APPROVED** [review]

File: image/DecodedSurfaceProvider.cpp (hunk 1 above)
Comment (kannanvijayan) [reply image/DecodedSurfaceProvider.cpp:124]: Thanks for pointing that out.  Will do.
