### PR TITLE
Fix sign in button to display when auth token expires

### LINKED ISSUE #558: Connection is not authenticated
I think that the browser has an old access token so it thinks i'm logged in, but app.replay.io has a different session...

Screen Shot 2021-10-15 at 4 51 06 PM

https://www.loom.com/share/8b9cd3ff07e449638ae350b2e44d131c

### PR DESCRIPTION
**Pull request by ryanjduffy**
* Changes `isLoggedIn` to check expiration date of token
* Changes `pingTelemetry` to use `XMLHttpRequest` because `fetch()` isn't always available but XHR seems to be

Verified by creating a new auth0 endpoint with a 60 second token life to test session expiration both when the browser is open and when it's closed.

### CODE REVIEW

File: devtools/server/actors/replay/telemetry.js [hunk 1]
```diff
@@ -20,17 +20,20 @@ function pingTelemetry(source, name, data) {
   );
   const browserSettings = { usePreallocated: !disablePreallocated };
 
-  fetch(url, {
```
Comment (loganfsmyth) [inline devtools/server/actors/replay/telemetry.js]: Maybe we need a line like this? https://searchfox.org/mozilla-central/source/browser/components/newtab/lib/TippyTopProvider.jsm#13

**Review by loganfsmyth — APPROVED** [review]
Looks good but I'd love to not have to use `XMLHttpRequest` if at all possible.

**Comment by ryanjduffy** [comment]
Thanks, @loganfsmyth . I looks around for examples of how to get at a copy of fetch but never found this one! Works great
